# Generated by Django 3.1.6 on 2023-04-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0027_auto_20230401_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='body_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='body_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='body_4',
        ),
    ]
