# Generated by Django 3.1.6 on 2023-04-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20230401_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
