# Generated by Django 3.1.6 on 2023-04-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_email_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
