# Generated by Django 3.1.6 on 2023-04-01 17:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField()),
                ('video_cover', models.ImageField(upload_to='Advisors/video_cover/')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('main_graph', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('graph_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('graph_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('graph_3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='Advisors/cover/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
