# Generated by Django 3.1.6 on 2023-04-01 18:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advizor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان بالعربية')),
                ('title_2', models.CharField(max_length=100, verbose_name='العنوان بالانجليزية')),
                ('cover', models.ImageField(upload_to='Advisors/advisor/', verbose_name='صورة الغلاف')),
                ('brief', models.TextField(max_length=250, verbose_name='وصف صغير')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='الفقرة الاولى')),
                ('created', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=160, verbose_name='العنوان بالانجليزية(دون اي مسافات)')),
                ('active', models.BooleanField(default=True, verbose_name='حالة النشاط')),
            ],
            options={
                'verbose_name_plural': 'تعديل اللجان',
            },
        ),
        migrations.DeleteModel(
            name='Advisors',
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name_plural': 'غلاف واجهة اللجان'},
        ),
    ]
