# Generated by Django 3.1.6 on 2023-04-02 05:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advisors', '0003_auto_20230401_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advizor',
            options={'verbose_name_plural': 'قائمة الممثلين'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name_plural': 'غلاف واجهة الممثلين'},
        ),
        migrations.AlterField(
            model_name='advizor',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='الفقرة الاولى'),
        ),
    ]
